Update dealerdirect/phpcodesniffer-composer-installer to fix error
This commit updates the package
dealerdirect/phpcodesniffer-composer-installer to the latest version to
fix the fatal error bellow when running any composer command. This
problem was caused by a bug in the package that was fixed in a later
version. For more information see https://github.com/Dealerdirect/phpcodesniffer-composer-installer/issues/59

```
$ composer install

(...)

PHP Fatal error:  Uncaught Error: Class 'Symfony\Component\Process\ProcessBuilder' not found in dealerdirect/phpcodesniffer-composer-installer/src/Plugin.php:118
Stack trace:
\#0 vendor/dealerdirect/phpcodesniffer-composer-installer/src/Plugin.php(103): Dealerdirect\Composer\Plugin\Installers\PHPCodeSniffer\Plugin->init()
\#1 /usr/share/php/Composer/Plugin/PluginManager.php(237): Dealerdirect\Composer\Plugin\Installers\PHPCodeSniffer\Plugin->activate()
\#2 /usr/share/php/Composer/Plugin/PluginManager.php(206): Composer\Plugin\PluginManager->addPlugin()
\#3 /usr/share/php/Composer/Installer/PluginInstaller.php(62): Composer\Plugin\PluginManager->registerPackage()
\#4 /usr/share/php/Composer/Installer/InstallationManager.php(173): Composer\Installer\PluginInstaller->install()
\#5 /usr/share/php/Composer/Installer/InstallationManager.php(160): Composer\Installer\InstallationManager->install()
\#6 /usr/share/php/Comp in vendor/dealerdirect/phpcodesniffer-composer-installer/src/Plugin.php on line 118

Fatal error: Uncaught Error: Class 'Symfony\Component\Process\ProcessBuilder' not found in vendor/dealerdirect/phpcodesniffer-composer-installer/src/Plugin.php:118
Stack trace:
\#0 /home/rodrigo/devel/automattic-hiring/synthetic-pistachio/vendor/dealerdirect/phpcodesniffer-composer-installer/src/Plugin.php(103): Dealerdirect\Composer\Plugin\Installers\PHPCodeSniffer\Plugin->init()
\#1 /usr/share/php/Composer/Plugin/PluginManager.php(237): Dealerdirect\Composer\Plugin\Installers\PHPCodeSniffer\Plugin->activate()
\#2 /usr/share/php/Composer/Plugin/PluginManager.php(206): Composer\Plugin\PluginManager->addPlugin()
\#3 /usr/share/php/Composer/Installer/PluginInstaller.php(62): Composer\Plugin\PluginManager->registerPackage()
\#4 /usr/share/php/Composer/Installer/InstallationManager.php(173): Composer\Installer\PluginInstaller->install()
\#5 /usr/share/php/Composer/Installer/InstallationManager.php(160): Composer\Installer\InstallationManager->install()
\#6 /usr/share/php/Comp in vendor/dealerdirect/phpcodesniffer-composer-installer/src/Plugin.php on line 118
```